___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
np.array([4,5,6])

array([4, 5, 6])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array([[1,2,3],[4,5,6],[1,1,1]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(0,10) #start, stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [54]:
newArr = np.arange(0, 49)

In [55]:
newArr.reshape(7,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5)) #pass a tuple to indicate the dimensions you want in (row,col) format

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0,10,3) #not to be confused with arange
# based on the output, it returns a 1-D array as there are only 1 set of brackets

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
np.linspace(0,5) #if not specified, it will generate 50 points/samples by default

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## eye

Creates an identity matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [36]:
np.random.rand(2)

array([0.11208377, 0.1656691 ])

In [56]:
np.random.rand(5,5) #Note that you don't need to pass in a tuple here 
# like you did for np.ones and np.zeros

array([[0.80793356, 0.49703627, 0.90603341, 0.52811553, 0.33272564],
       [0.41983191, 0.07220806, 0.42700608, 0.5093052 , 0.91663049],
       [0.72133674, 0.88921107, 0.92292775, 0.2875626 , 0.68470149],
       [0.45091943, 0.77925144, 0.19741662, 0.84094109, 0.9561508 ],
       [0.70079003, 0.56541458, 0.86799728, 0.73900396, 0.3224201 ]])

In [57]:
np.random.rand(3,3)

array([[0.14875535, 0.05526886, 0.71901082],
       [0.21022484, 0.40524697, 0.99625998],
       [0.74372935, 0.95862477, 0.22587029]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [38]:
np.random.randn(2)

array([-1.39452669,  0.49964912])

In [39]:
np.random.randn(5,5)

array([[-0.64878226,  0.6426661 ,  0.32513643,  1.30730835,  0.52842442],
       [ 0.08018354, -0.22051278, -0.2095509 ,  0.0121978 ,  0.87080737],
       [ 0.8214866 , -1.01361964,  0.34010468,  0.2849941 ,  0.88085024],
       [ 1.09972355,  1.40476887, -0.47967928, -0.89106612,  1.15250692],
       [ 2.03964764, -0.42619635,  0.93917394, -1.87168477,  0.37535525]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [40]:
np.random.randint(1,100)

35

In [42]:
np.random.randint(1,100,10)

array([42, 60, 72,  7, 22, 40, 19, 99, 72, 51])

In [58]:
np.random.randint(1,100,(5,5)) #unlike rand and randn, you need to specify the shape in a tuple here

array([[99, 26, 43,  1, 99],
       [25, 20, 87,  6, 16],
       [83,  4, 48, 23, 14],
       [27, 43, 93, 21, 34],
       [37,  7, 13, 48, 52]])

In [59]:
np.random.randint(0,10,(3,3))

array([[1, 3, 9],
       [9, 5, 7],
       [5, 6, 2]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [46]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([ 2,  3, 17, 34, 34, 31, 21, 20,  1,  4])

## Reshape
Returns an array containing the same data with a new shape.

In [60]:
arr.reshape(5,5) #similar to rand and randn, no need to specify with tuple

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [61]:
ranarr

array([ 2,  3, 17, 34, 34, 31, 21, 20,  1,  4])

In [62]:
ranarr.max()

34

In [63]:
ranarr.argmax() #returns the index of the maximum value in the array

3

In [64]:
ranarr.min()

1

In [66]:
ranarr.argmin() #returns the index of the minimum value in the array

8

In [83]:
testArr = np.array([[1,2],[3,4]])
testArr

array([[1, 2],
       [3, 4]])

In [84]:
testArr.shape

(2, 2)

In [78]:
testArr.min()

1

In [79]:
testArr.max()

4

In [82]:
testArr.argmin() #assuming flattened array (which isnt ideal)

0

In [85]:
np.unravel_index(testArr.argmin(),testArr.shape) #using argmin for 2-D array

(0, 0)

In [86]:
testArr.argmax() #assuming flattened array (which isnt ideal)

3

In [87]:
np.unravel_index(testArr.argmax(),testArr.shape) #usuing argmax for 2-D array 

(1, 1)

## Shape

Shape is an attribute that arrays have (not a method):

In [91]:
# Vector
reshape_from_vector_to_mat = arr.reshape(5,5)

In [92]:
reshape_from_vector_to_mat.shape

(5, 5)

In [94]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [95]:
arr.reshape(1,25).shape

(1, 25)

In [96]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [97]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [93]:
arr.dtype

dtype('int64')

# Great Job!